### ISSUE TITLE
Also remove unlisted buffers?

### ISSUE THREAD

**Issue by davidsierradz** [Asheq/close-buffers.vim#7]
If I see `:buffers!` there is a lot of buffers there that can't be removed with `close-buffers.vim`.

Thanks

**Comment by Asheq** [comment]
This shouldn't be a problem to add. I will probably get to it next week though.

Some background: Currently, close-buffers.vim uses the `bdelete` command under the hood. `bdelete` unloads buffers (frees memory allocated for their contents) and removes them from the buffer list. However, some auxiliary information about them are still retained (e.g. marks) which is why they continue to show up in the expanded buffer list as "unlisted". Buffers can be _completely_ deleted with `bwipeout` instead of `bdelete`.

My plan as of now is to rename/alias the existing commands in close-buffers.vim be more consistent with the built-in vim commands.

So these:
```
:CloseBuffersMenu
:CloseOtherBuffers
:CloseHiddenBuffers
:CloseNamelessBuffers
:CloseSelectedBuffers
:CloseAllBuffers
:CloseThisBuffer
```
will become the following. They will continue to operate on only listed buffers and `bdelete` them:
```
:Bdelete -menu
:Bdelete -other
:Bdelete -hidden
:Bdelete -nameless
:Bdelete -selected
:Bdelete -all
:Bdelete -this
```

I will then add an equivalent set of `:Bwipeout` commands below. They will operate on both listed and unlisted buffers and `bwipeout` them:
```
:Bwipeout -menu
:Bwipeout -other
:Bwipeout -hidden
:Bwipeout -nameless
:Bwipeout -selected
:Bwipeout -all
:Bwipeout -this
:Bwipeout -unlisted
```
Let me know if you have any feedback.

**Comment by davidsierradz** [comment]
Thanks, I think this is a nice way to handle it.

**Comment by jbbudzon** [comment]
Not trying to badger you but any idea what happened with this? It seems like a solid enhancement request and I've been wanting similar functionality lately. Was worried this may have gotten lost as the issue was closed out before any code was implemented!

**Comment by Asheq** [comment]
I am working on it on another branch: https://github.com/Asheq/close-buffers.vim/tree/change-command

I have been a bit busy so it's coming along slowly, but will try to finish it soon.

This other branch has these commands now to replace the old ones:
```
:Bdelete Menu
:Bdelete Other
:Bdelete Hidden
:Bdelete Nameless
:Bdelete Select
:Bdelete All
:Bdelete This
```

I need to add these, but I want to make sure the code is DRY:

```
:Bwipeout Menu
:Bwipeout Other
:Bwipeout Hidden
:Bwipeout Nameless
:Bwipeout Select
:Bwipeout All
:Bwipeout This
:Bwipeout Unlisted
```

**Comment by Asheq** [comment]
@jbbudzon @davidsierradz 

I would like your input on something.

The `Bdelete` commands operate on buffers that are listed and always leave unlisted buffers alone.

I am trying to decide if the `Bwipeout` commands should:

1. Also work only on listed buffers, unless explicitly using `Bwipeout Unlisted`
OR
2. Both listed _and_ unlisted buffers.

For example, if I have the following buffers:

- `listed buffer 1` (not active)
- `listed buffer 2` (active)
- `unlisted buffer 1`
- `unlisted buffer 2`

If a user executes `Bwipeout Other`, I know for sure that listed buffer 1 should be wiped out. But should `unlisted buffer 1` and `unlisted buffer 2` also be wiped out? Or should they be left alone until the user explicitly executes `Bwipeout Other`.

I would appreciate your input; what does your intended use-case call for?

**Comment by jbbudzon** [comment]
@Asheq I think keeping it simple for now will work well 👍 The parameter isn't necessary for my workflow as I'll either be deleting all listed buffers or wiping all both listed and unlisted buffers.

**Comment by Asheq** [comment]
The `Bwipeout` commands (e.g. `:Bwipeout menu`) are ready in the `change-command` branch of this repo. If you can, please test it and let me know if things are working like you expect. @jbbudzon @davidsierradz 

I'll merge this into the master branch in a few days.

---

If you are using **vim-plug**, you can use the `change-command` branch by changing this line in your vimrc:
```
Plug 'Asheq/close-buffers.vim'
```

to this:
```
Plug 'Asheq/close-buffers.vim', { 'branch': 'change-command' }
```
Then restart vim and execute `:PlugUpdate`

**Comment by jbbudzon** [comment]
Will do!

**Comment by jbbudzon** [comment]
Worked like a charm. Thanks!!

**Comment by davidsierradz** [comment]
Can confirm, working good, thanks!

**Comment by Asheq** [comment]
Great, thanks for testing! I will give it a couple days before merging into master.

**Comment by Asheq** [comment]
Merged to master
